version: '3'
services: 
  # flask:
  #   build:
  #     context: .
  #     dockerfile: './compose/Flask'
  #     command: 'flask run --host 0.0.0.0 --port 8000 --with-threads'
  #     environment: 
  #       FLASK_APP: 'eyefundus/flask.py'
  #     ports: 
  #       - "8000:8000"
  #     volumes: 
  #       - .:/eyefundus
  #     depends_on:
  #       - tensorflow
  tensorflow:
    build:
      context: .
      dockerfile: './compose/Tensorflow'
    command: "jupyter notebook --allow-root"
    volumes:
      - ./eyefundus/tensorflow:/tensorflow
    ports:
      - "8888:8888"
